<?php

use App\Entity\Department;
use PHPUnit\Framework\TestCase;

class DepartmentTest extends TestCase
{
    protected $department;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->department = new Department();
    }

    public function testSettingDepartmentName(){
        $name = 'Limpieza';
        $this->department->setName($name);

        $this->assertEquals($name, $this->department->getName());
    }

    public function testSettingDepartmentCode(){
        $code = 'Limp-03';
        $this->department->setCode($code);

        $this->assertEquals($code, $this->department->getCode());
    }
}