<?php

use App\Entity\Calendar;
use App\Entity\Festive;
use PHPUnit\Framework\TestCase;

class FestiveTest extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->festive = new Festive();
    }

    public function testSettingFestiveName(){
        $name= 'Christmas';
        $this->festive->setName($name);

        $this->assertEquals($name, $this->festive->getName());
    }

    public function testSettingFestiveDate(){
        $date= new DateTime();
        $this->festive->setDate($date);

        $this->assertEquals($date, $this->festive->getDate());
    }

    public function testSettingFestiveCalendar(){
        $calendar = new Calendar;
        $this->festive->setCalendar($calendar);

        $this->assertEquals($calendar, $this->festive->getCalendar());
    }


}