<?php

use App\Entity\Calendar;
use App\Entity\Justify;
use App\Entity\Petition;
use App\Entity\User;
use PHPUnit\Framework\TestCase;

class PetitionTest extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->petition = new Petition();
    }

    public function testSettingPetitionInitialDate(){
        $initial = new DateTime();
        $this->petition->setInitialDate($initial);

        $this->assertEquals($initial, $this->petition->getInitialDate());
    }

    public function testSettingPetitionFinalDate(){
        $final = new DateTime();
        $this->petition->setFinalDate($final);

        $this->assertEquals($final, $this->petition->getFinalDate());
    }

    public function testSettingPetitionDuration(){
        $duration = 9;
        $this->petition->setDuration($duration);

        $this->assertEquals($duration, $this->petition->getDuration());
    }

    public function testSettingPetitionState(){
        $state = 'PENDING';
        $this->petition->setState($state);

        $this->assertEquals($state, $this->petition->getState());
    }

    public function testSettingPetitionType(){
        $type = 'Vacation';
        $this->petition->setType($type);

        $this->assertEquals($type, $this->petition->getType());
    }

    public function testSettingPetitionReason(){
        $reason = 'Vacation';
        $this->petition->setReason($reason);

        $this->assertEquals($reason, $this->petition->getReason());
    }

    public function testSettingPetitionDate(){
        $date = new DateTime();
        $this->petition->setPetitionDate($date);

        $this->assertEquals($date, $this->petition->getPetitionDate());
    }

    public function testSettingPetitionEmployee(){
        $employee = new User();
        $this->petition->setEmployee($employee);

        $this->assertEquals($employee, $this->petition->getEmployee());
    }

    public function testSettingSupervisor(){
        $supervisor = new User();
        $this->petition->setSupervisor($supervisor);

        $this->assertEquals($supervisor, $this->petition->getSupervisor());
    }

    public function testSettingCalendar(){
        $calendar = new Calendar();
        $this->petition->setCalendar($calendar);

        $this->assertEquals($calendar, $this->petition->getCalendar());
    }

    public function testSettingJustify(){
        $justify = new Justify();
        $this->petition->setJustify($justify);

        $this->assertEquals($justify, $this->petition->getJustify());
    }
}