twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        role_admin: '%role_admin%'
        role_supervisor: '%role_supervisor%'
        role_employee: '%role_employee%'
        locales: '%app.locales%'
        en: '%en%'
        es: '%es%'
        ca: '%ca%'
        eu: '%eu%'
        accepted: '%accepted%'
        pending: '%pending%'
        denied: '%denied%'
        vacation: '%vacation%'
        absence: '%absence%'

when@test:
    twig:
        strict_variables: true
